---
kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: matthis974/dockspace
    dockerfile: Dockerfile
    tags: herobot2
