name: HeroBotBuild
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matthis974/herobot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
       steps:
  deploy:
    on:
      push:
        branches:
          - master
    runs-on: ubuntu-latest
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://admin.alivecreation.fr/portainer/api/webhooks/d000bcb8-c2f7-4ad4-bd7a-43143c645cae
