name: HeroBotBuild

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Submodules Init
      uses: chris-short/github-action-git-submodules@v0.1.0

    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview9-014004
    - name: Build with dotnet
      run: dotnet build --configuration Release
